package api

import (
	"net/http"

	_ "github.com/CallumLewisGH/Boondock-Service-Base/docs" // docs is generated by Swag CLI
	shopping "github.com/CallumLewisGH/Boondock-Service-Base/internal/domain/models/Shopping"
	"github.com/gorilla/mux"
	httpSwagger "github.com/swaggo/http-swagger"
)

// Server holds the router and shopping items
type Server struct {
	*mux.Router
	ShoppingItems []shopping.Item
}

// @title Boondock-Service-Base API
// @version 1.0
// @description This is a sample shopping list API
// @host localhost:8080
// @BasePath /
func NewServer() *Server {
	s := &Server{
		Router:        mux.NewRouter(),
		ShoppingItems: []shopping.Item{},
	}

	// Swagger
	s.Router.PathPrefix("/swagger/").Handler(httpSwagger.Handler(
		httpSwagger.URL("/swagger/doc.json"), //The url pointing to API definition
	))

	return s
}

func (s *Server) HandleFunc(pattern string, handler http.HandlerFunc) {
	s.Router.HandleFunc(pattern, handler)
}
