basePath: /
definitions:
  api.Item:
    description: Shopping item information
    properties:
      id:
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
      name:
        example: Milk
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the base service for boondocks API
  title: Boondock-Service-Base API
  version: "1.0"
paths:
  /items:
    get:
      description: Get full shopping list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.Item'
            type: array
      summary: List all shopping items
      tags:
      - items
swagger: "2.0"
